export interface EventItem {
  id: number
  category: string
  title: string
  description: string
  location: string
  date: string
  time: string
  petsAllowed: boolean
  organizer: string
}
export interface NewEventItem {
  id: string
  category: string
  title: string
  description: string
  organinser: string
  location: string
  date: string
  time: string
}

export interface ServerResponseEvents {
  events: EventItem[]
}

export interface RadioOptionsType {
  label: string
  value: number
}
export type RadioOptionsTypes = RadioOptionsType[]

export type SelectOptions = string[]
// Generated by https://quicktype.io

export interface EtsyListings {
  count: number
  results: EtsyResult[]
  params: Params
  type: string
  pagination: Pagination
}

export interface Pagination {
  effective_limit: number
  effective_offset: number
  next_offset: number
  effective_page: number
  next_page: number
}

export interface Params {
  limit: number
  offset: number
  page: null
  shop_id: string
  keywords: null
  sort_on: string
  sort_order: string
  min_price: null
  max_price: null
  color: null
  color_accuracy: number
  tags: null
  taxonomy_id: null
  translate_keywords: string
  include_private: number
}

export interface EtsyResult {
  listing_id: number
  state: State
  user_id: number
  category_id: null
  title: string
  description: string
  creation_tsz: number
  ending_tsz: number
  original_creation_tsz: number
  last_modified_tsz: number
  price: string
  currency_code: CurrencyCode
  quantity: number
  sku: any[]
  tags: string[]
  materials: string[]
  shop_section_id: number | null
  featured_rank: number | null
  state_tsz: number
  url: string
  views: number
  num_favorers: number
  shipping_template_id: number | null
  processing_min: number | null
  processing_max: number | null
  who_made: WhoMade
  is_supply: string
  when_made: boolean | WhenMadeEnum
  item_weight: null
  item_weight_unit: ItemWeightUnit | null
  item_length: null
  item_width: null
  item_height: null
  item_dimensions_unit: ItemDimensionsUnit | null
  is_private: boolean
  recipient: null
  occasion: null
  style: string[] | null
  non_taxable: boolean
  is_customizable: boolean
  is_digital: boolean
  file_data: string
  should_auto_renew: boolean
  language: Language
  has_variations: boolean
  taxonomy_id: number
  taxonomy_path: string[]
  used_manufacturer: boolean
  is_vintage: boolean
  Images: EtsyImage[]
}

export interface EtsyImage {
  listing_image_id: number
  hex_code: string
  red: number
  green: number
  blue: number
  hue: number
  saturation: number
  brightness: number
  is_black_and_white: boolean
  creation_tsz: number
  listing_id: number
  rank: number
  url_75x75: string
  url_170x135: string
  url_570xN: string
  url_fullxfull: string
  full_height: number
  full_width: number
}

export enum CurrencyCode {
  Gbp = "GBP",
}

export enum ItemDimensionsUnit {
  In = "in",
  Mm = "mm",
}

export enum ItemWeightUnit {
  G = "g",
  Oz = "oz",
}

export enum Language {
  EnUS = "en-US",
}

export enum State {
  Active = "active",
}

export enum WhenMadeEnum {
  The2010_2019 = "2010_2019",
  The2020_2021 = "2020_2021",
}

export enum WhoMade {
  IDid = "i_did",
  SomeoneElse = "someone_else",
}
